# dipstick.earth :80 — redirect to HTTPS only. No WSGI here (see the -le-ssl
# file for why).
<VirtualHost *:80>
    ServerName dipstick.earth
    ServerAlias www.dipstick.earth
    ServerAdmin alex@alexhornstein.com

    RewriteEngine on
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/
    RewriteRule ^ https://dipstick.earth%{REQUEST_URI} [END,NE,R=permanent]

    LogLevel info
    ErrorLog  /home/japhy/logs/dipstick.earth-error.log
    CustomLog /home/japhy/logs/dipstick.earth-access.log combined
</VirtualHost>
