# Generated by Django 4.2.15 on 2026-09-22 05:01

from django.db import migrations, models
import django.db.models.deletion
import stickers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=120, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('group', models.CharField(choices=[('fish', 'Fish'), ('invertebrate', 'Invertebrate'), ('amphibian', 'Amphibian'), ('reptile', 'Reptile'), ('bird', 'Bird'), ('mammal', 'Mammal'), ('plant', 'Plant or algae'), ('other', 'Something else')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional blurb shown on the species page.')),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=stickers.models.upload_to)),
                ('media_kind', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('wildlife_investigator', models.CharField(blank=True, help_text='Who pointed the dipstick. Shown on the sticker back.', max_length=120)),
                ('location', models.CharField(blank=True, help_text='Free text — geocoded to lat/lng on save.', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('submitter_email', models.EmailField(blank=True, help_text='Optional, private. Never rendered in a template.', max_length=254)),
                ('moderator_note', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stickers', to='stickers.species')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='stickers_st_status_f8b2d1_idx')],
            },
        ),
    ]
