# Generated by Django 4.2.15 on 2026-09-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='shape',
            field=models.CharField(blank=True, default='', help_text='Die-cut outline. Leave on auto to spread the shapes evenly across the sheet.', max_length=40),
        ),
    ]
