# Generated by Django 4.2.15 on 2026-09-22 05:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_sticker_shape'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='sticker',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sticker',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['deleted_at'], name='stickers_st_deleted_236799_idx'),
        ),
    ]
