# Generated by Django 4.2.15 on 2026-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_alter_sticker_options_alter_sticker_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='focal_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='sticker',
            name='focal_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='sticker',
            name='zoom',
            field=models.FloatField(default=1.0),
        ),
    ]
