# Generated by Django 4.2.15 on 2026-09-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_sticker_focal_x_sticker_focal_y_sticker_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='focal_x',
            field=models.FloatField(blank=True, default=0.5),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='focal_y',
            field=models.FloatField(blank=True, default=0.5),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='zoom',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
