# Generated by Django 4.2.15 on 2026-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_alter_sticker_focal_x_alter_sticker_focal_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='media_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='media_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
